version: '3.8'

services:
  php:
    build:
      context: ./docker/php
    container_name: presentation-php-fpm
    restart: always
    volumes:
      - ./:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - doeb3-network

  apache:
    build:
      context: ./docker/apache
    container_name: Presentation
    restart: always
    ports:
      - "7080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - php
    networks:
      - doeb3-network

networks:
  doeb3-network:
    driver: bridge
